import { Note } from '../types/Notes';

export const Notes: Note[] = [
  {
    id: 1,
    title: 'Keywords are missing',
    description:
      'Keyword’s are missing. And still you haven’t done this thing this thing should be done by you by this week.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
  {
    id: 2,
    title: 'Review content',
    description:
      'Review the content and check for any errors. Also, ensure the content is easy to understand.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
  {
    id: 3,
    title: 'Check for typos',
    description: 'Check for any typos in the content. If found, correct them.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
  {
    id: 4,
    title: 'Review images',
    description:
      'Review the images and ensure they are clear, legible, and have appropriate alt tags.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
  {
    id: 5,
    title: 'Check for broken links',
    description:
      'Check for any broken links in the content. If found, fix them.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
  {
    id: 6,
    title: 'Review table formatting',
    description:
      'Review the table formatting and ensure it is correct and easy to understand.',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    isPinned: false,
    tags: [],
    isArchived: false,
    isDeleted: false,
    userId: 0,
    isPublic: false,
    isFeatured: false,
    isStarred: false,
    isLocked: false,
  },
];
